centrefornetzero/domestic-heating-abm

- simulation/agents.py
- simulation/constants.py
- simulation/costs.py
- simulation/tests/test_agents.py
- Adds method to identify "upgradable" insulation elements. An insulation element refers to the household's roof, windows, or walls. It's upgradable if the energy efficiency is less than 5 (the maximum score from the EPC certificate).
- Adds method to get a cost estimate per element. This is segmented as per the source BEIS report, as different property segments can materially influence costs (e.g. the cost to add wall insulation to a mid-terrace house is very different to a detached house).
> Add household methods to get costs for insulation elements

- simulation/agents.py
- simulation/tests/test_agents.py
- Adds household method to choose insulation elements, by price ASC
- Adds household method to decide how many insulation elements to install, based upon relative frequency of households installing 1,2 or 3 insulation measures during renovation from the VERD Project, 2012-2013 (UK Data Service. SN: 7773, http://doi.org/10.5255/UKDA-SN-7773-1)
- Adds household method to install these N measures: update the respective energy efficiency of the element, and update overall EPC +1 grade per measure
> Add household functionality to choose and install insulation

- simulation/agents.py
- simulation/model.py
- simulation/tests/test_agents.py
- simulation/tests/test_model.py
- Adds a default set of heating systems to `CnzAgentBasedModel`
- Adds household attribute `potential_epc`
- Adds household property `is_heat_pump_suitable` (based on property archetype and potential_epc)
- Adds household method to fetch their heating system options, which subsets the model default heating systems, based on `is_heat_pump_suitable`, `is_heat_pump_aware`, and `off_gas_grid` statuses
> Add functionality for households to get their heating system options

- simulation/agents.py
- simulation/constants.py
- simulation/tests/test_agents.py
- Add Weibull parameters approximately corresponding to a distribution of discount rates for households selecting heating system related purchases (Individual Time Preferences and Energy Efficiency - NBER Working Paper No. 20969)
- Add household method to fetch a discount rate value from this distribution, based on wealth percentile. There is an inverse relationship between discount rate and wealth.
> Households have discount rates linked to wealth percentile

- simulation/agents.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/test_agents.py
- simulation/tests/test_model.py
- Initialise households with `heating_system_install_date`, to replace household `heating_system_age`. This avoids us needing to update heating system age at each timestep.
- Add household method to evaluate if heating is functioning, based on age of heating system and Weibull hazard function parameters
- Modify `household.get_heating_system_options` so heat pumps are not options during a breakdown (due to high industry lead times), unless a household already has a heat pump installed. In that event, the specific type of heat pump already installed (air/ground source) remains an option.
> Households have heating system breakdowns, and restricted system choices at breakdown

- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- simulation/costs.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_collectors.py
- simulation/tests/test_costs.py
- simulation/tests/test_model.py
- Costs of unit, install and fuel prices are added as constants
- Households fetch unit and install costs (based on required capacity for heat pumps, or coarse property band sizes for boilers). Install costs depend on whether it's a like-for-like replacement, or a switch (which have implied additional costs, like decommissioning redundant system parts).
- Households have an estimated annual kwh heat demand, based on their floor area. Note that we ignore any impact of EPC for the time being. This aligns to some empirical studies which suggest households often increase energy usage after improving efficiency, to further increase comfort levels at the same cost.
- Households evaluate future fuel bills based on some number of "look ahead" years (defined at the model level). For example, while …
> Households fetch costs of heating systems (unit, install, and fuel costs)

- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- `EventTrigger.EPC_C_UPGRADE` added, which is associated with particular count of insulation upgrade requirements to reach EPC C (unlike a renovation event)
- Update household methods to choose number of insulation elements - to accept an event_trigger and return different output depending on whether an `EventTrigger.RENOVATION` or `EventTrigger.EPC_C_UPGRADE`
- Update model to accept `heating_system_hassle_factor`, which suppresses likelihood of a "hassle-y" heating system being chosen by a household
- Add household methods to get total heating system costs, get chosen insulation element costs, evaluate whether a heating system is a "hassle" or not, and choose a heating system (based on costs + hassle)
- Update `household.step()` to reflect the above
> Households choose heating systems based on costs and hassle

- abm.py
- simulation/agents.py
- simulation/collectors.py
- tests/test_abm.py
- Add various household collectors for more comprehensive simulation tracking 
- Small modifications to household methods to resolve consistency issues and bugs observed during analysis of simulation output, or to add various household attributes for simulation logging (e.g. prices of heating types seen at a heating decision)
- modify `AgentBasedModel.run()` so agent_callables which evaluate to `False` (e.g. `is_renovating`) are stored as  `False` (and not `None`) in the agent's history
> Add fuller simulation tracking

- simulation/constants.py
- simulation/costs.py
- simulation/tests/test_costs.py
- Adds a fixed constant cost for boiler installation, as the existing figures reflect the costs of the unit only.
- Updates the minimum KW capacity of heat pumps installed in practice, reflecting advice from heat pump installation experts consulted
- Adds factors which discount the costs of 2nd+ time heat pump installs -- as the figures reflect "first time" installation costs like pipework, radiator upgrades and drilling boreholes which will not apply to a repurchase of the same heat pump system. This is particularly true of ground source heat pumps.
> Update heating system costs (installation, re-installation, and min. heat pump capacity required)

- simulation/agents.py
- simulation/constants.py
- simulation/tests/test_agents.py
- Reorder `class Epc(enum.Enum)`, so value increases as EPC increases
- Refactor associated logic that makes use of epc enum values
> Reorder epc enum class so EPC A takes highest value

- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- simulation/costs.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_costs.py
In order to reconcile the outputs of the ABM against historical uptake, we need to reflect the conditions of the Domestic RHI in the ABM, which has been live since April 2014 (https://www.ofgem.gov.uk/environmental-and-social-schemes/domestic-renewable-heat-incentive-domestic-rhi). This PR:
- Adds a function to calculate the payments that households would be likely to receive under the RHI
- Passes an intervention label as a command line arg to the model
- Updates a household's method to compute total cost of a given heating system, to subtract any relevant subsidy
> Add RHI intervention to support simulation validation over historical periods

- simulation/__main__.py
- simulation/agents.py
- simulation/costs.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_costs.py
- Add discount factor to the model which represents the % by which current air source heat pump costs will have fallen, by the end of 2022. This factor linearly changes over the year 2022, reaching a user-specified or default value at the end of 2022.
- Modify cost calculations to reflect this discount factor
- Test that ASHP costs become cheaper across 2022 (when this discount factor is non-zero)
Note that this PR enables _deterministic_ ASHP price changes to be reflected in the simulation. A future PR could incorporate a learning rate calculation based upon the number of units sold in the simulation, if necessary.
> ASHP costs are linearly discounted up to a user-specified factor by the end of 2022

- simulation/agents.py
- simulation/collectors.py
- simulation/tests/test_agents.py
- Update of a household's heating system status is moved from `household.install_heating_system()` to `household.update_heating_status()`. This ensures that the model collector for this attribute will obtain value `False` for the step in which a household's heating system has broken down (previously, it is updated back to `True` before the step is completed). A related test around heating system installation is modified accordingly.
- Add household attribute `household_heating_system_prior`, which is initialised to `None`, and populated with a heating system at every time step after a household has changed heating system. This is to facilitate downstream analyses on breakdown events on very large files
- Add collectors for `household_heating_functioning` and …
> Add fuller simulation tracking - prior heating system and functioning status

- simulation/__main__.py
- simulation/model.py
- simulation/tests/test_model.py
- Setting this arg to `True` means that all households in the simulation will be initialised with `is_heat_pump_suitable_archetype=True`, instead of as per the source file (in which mid-terraced houses and flats are categorised as unsuitable)
- Doing so is important for downstream analyses on the possible ranges of outcomes, as HP suitability is a contested topic -- the source dataset represents a conservative estimate of suitability, while the override represents the most optimistic
> add command line arg to override heat pump suitability to True for all households

- simulation/__main__.py
- simulation/agents.py
- simulation/collectors.py
- simulation/constants.py
- simulation/costs.py
- simulation/model.py
- simulation/tests/test_agents.py
- simulation/tests/test_costs.py
- simulation/tests/test_model.py
- Adds `boiler_upgrade_scheme` as an intervention type, as per the details outlined [here](https://www.gov.uk/government/news/plan-to-drive-down-the-cost-of-clean-heat) and [here](https://www.homebuilding.co.uk/advice/boiler-upgrade-scheme).
- Over the calendar dates that the grant is active, households will be eligible for the grant when switching to a heat pump -- if the total model budget of £450mil is not exceeded. In practice, this cap is not likely to be enforced when modelling at a sub-UK level, but it is nonetheless of interest to track total uptake within a simulation. Additional logic is added to DomesticHeatingABM to sum and store the grants used by households, and collector is added to log this total value.
- New household attributes `boiler_upgrade_grant_available` and …
> Add boiler upgrade scheme intervention

- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- This PR modifies a number of default parameters and the weights used when choosing between systems, as part of the process of reconciling the outputs of the ABM with historical heat pump uptake under the RHI. The changes to the latter mean that households weight heating system options with greater discrimination; previously the function weights 'plateaued' when a system was priced at ~40% of a household's budget or lower, while the updated function continues to weight heating systems more highly as they fall below 40% of the budget (i.e. households prefer a system which is 20% of their budget over a heating system which is 30% or 40% of their budget).
- As part of this calibration, it was also found that households who find all heating system options highly unaffordable approximately …
> Update model parameters and heating decision weights post-calibration with RHI uptake

- simulation/costs.py
- Revises fuel pence per kwh estimates to align with [Energy Savings Trust ](https://energysavingtrust.org.uk/about-us/our-data/ (England, Scotland and Wales)) estimates, which were last updated in November 2021 and based on predicted fuel prices for 2022
> Update prices of fuel per kWh used across simulation

- simulation/__main__.py
- simulation/agents.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_main.py
- Update `--intervention` arg to enable multi-intervention simulations in the future, such as Boiler Upgrade Scheme + Boiler Ban
- As not all interventions we plan to implement will result in a subsidy seen by households (e.g. boiler ban), the logic used in `household.get_total_heating_system_costs()` is amended to anticipate this (previously, a £0 subsidy would only be assigned if model intervention attribute was empty)
> Update cl arg --intervention to pass multiple interventions to simulation

- simulation/__main__.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_main.py
- Adds gas and oil boiler ban, as of the `--gas-oil-boiler-ban-date` cl arg (default: 2035-01-01)
- Instead of being a static attribute set at model initialisation, the set of heating systems available is revised into a model property, which gets re-evaluated (based upon the model interventions list, boiler ban date and current model datetime) whenever households make heating decisions
- Note that post-ban, some households can have no heating systems available to them -- e.g. due to unsuitability for heat pumps or electric boilers, and/or because the replacement is triggered by `EventTrigger.BREAKDOWN`, in which heat pumps are not available due to the high lead times required. As for the case where households find all heating system options highly unaffordable, the fallback behaviour here …
> Add intervention - gas and oil boiler ban

- Pipfile
- Pipfile.lock
- simulation/__main__.py
- simulation/tests/test_main.py
Compare pickle and JSON output in the same test. If they both fail, then we know it's a problem with the ABM class. If only the JSON fails, but the pickle doesn't, then we know it's a problem with the JSON (de)serialization. If the pickle fails but the JSON doesn't, well, I'm not sure what that means. Let's hope that doesn't happen!
> Write pickle to try and identify cause of flaky test

- simulation/agents.py
- simulation/collectors.py
- simulation/tests/test_agents.py
- Modifies `household.get_heating_system_options()` such that when a gas/boiler ban is active, all (heat pump suitable) households will consider heat pumps -- regardless of the `EventType`, and regardless of their `is_heat_pump_aware` attribute set at household init.
> Households aware of heat pumps and consider them in breakdowns if boiler ban active

- simulation/__main__.py
- simulation/costs.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_costs.py
- simulation/tests/test_main.py
- simulation/tests/test_model.py
- Deprecates `model.air_source_heat_pump_discount_factor_2022` and replaces with `model.air_source_heat_pump_price_discount_date`, enabling the user to more flexibly pass in a (stepped) discount schedule for ASHPs
> Air source heat pump costs change according to specified date schedule

- simulation/__main__.py
- simulation/agents.py
- simulation/collectors.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_model.py
- Enables user to pass in a factor for annual heat pump installer growth, which in turn with defaults specified for the time taken to install a heat pump, limits the number of heat pumps which can be installed in a given step. In this way, we prevent heat pump uptake  exceeding some plausible/forecasted heat pump installer capacity.
- With the defaults provided, the implied heat pump installation capacity is 3,400 installs/month or 40k installs/year, which approximately aligns with estimates of 35k currently being installed in the UK per year ([page 8](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1026356/domestic-offgg-consultation.pdf))
- Similarly to the Boiler Upgrade Scheme budget, the heat pump installer count is scaled to the actual …
> Add heat pump installer capacity to cap heat pump uptake

- simulation/costs.py
- simulation/tests/test_costs.py
- Floors the price of an air source heat pump to the price that a given household would pay for a gas boiler. Note that all decommissioning costs sit independently of projected unit costs - therefore for a household _switching_ heating system, they will still experience these decommissioning costs on top of the floored price.
- Also refactors the function `costs.get_unit_and_install_costs()` for clearer code in the process.
> Add floor for ASHP cost at price of a gas boiler

- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/common.py
- simulation/tests/test_agents.py
- simulation/tests/test_main.py
- Context: Prior to this PR, households would always ignore the existence of an upcoming ban and react only when the ban is live. This results in a sharp, angular uptake in HPs as of the ban date.
- This PR introduces the possibility of households responding to the ban before it is live - a proportion of households will exclude to-be-banned systems (oil/gas boilers) from their heating system options if the ban has been announced. The proportion of households doing this depends upon the time til the ban. When the ban is live, this is always 100%. When the ban is more than 10 years away, this is always 0%. When the ban is between 0-10 years away, this is determined by a parameterised sigmoid curve (see below). The curve's parameters can be considered placeholder values subject to further …
> Households exclude to-be-banned systems as options, ahead of ban

- simulation/__main__.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/test_model.py
- Updates the default HP installer growth rate to 56.5%. Rationale:
> HPs per year (by 2028) = 600,000
> HPs installed by 1 installer per year = 24
> Implied installer count in at 2028 = 25,000
> Starting from a baseline of 1,700 HP installers, a default annual growth rate of 56.5% would result in ~25k installers in 6 years time (by 2028).
- Caps the total number of HP installers to avoid exponential growth under certain inputs. The current ratio of households to gas engineers is used as a floor, and implicitly assumes a 1:1 replacement of gas engineer to heat pump engineers in the future.
> Update default hp installer growth rate and cap total installer count

- simulation/constants.py
- Improves upon the estimated time it takes for one installer to install one heat pump, and the number of HP installers as of the end of 2021 - using a source from the Heat Pump Association
- Scales HEAT_PUMP_INSTALLER_COUNT, a UK-wide figure, to the England and Wales population
> Update HP installer related constants for new sources

- k8s/job.jsonnet
- simulation/__main__.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/common.py
- Refactor the count of heat pump installers at start of simulation, so it's a cl arg instead of a hard-coded constant. This provides us with flexibility over simulations for the historical RHI scenario. Possible adjustments to HP installer count over this historical scenario in a future PR.
- Updates the default HP installer growth rate to `0.48`, a value which reflects the default HP installer initial count of 2_800 experiencing this annual growth over 6 years, to reach 33,700 installers in 2028 (CCC Balanced Pathway scenario)
- Update default HP awareness to a value of `0.25` and "high awareness" scenarios to double that, `0.5`. 25% reflects the proportion of people who know "a lot or a fair amount" about LC heating systems according to the [BEIS Public Attitudes Tracker (Autumn 2021, …
> Modify simulation parameters and scenario specifications

- simulation/__main__.py
- simulation/tests/test_main.py
By default, we want to obtain a complete year of simulation results for 2022.
> Update default start-date of simulation to 2022-01-01

- Pipfile
- Pipfile.lock
Reverts centrefornetzero/domestic-heating-abm#114.
Going to disable Dependabot - no real need to upgrade anything now we're drafting the report.
> Revert "Bump pandas from 1.4.0 to 1.4.1"

- simulation/__main__.py
- simulation/constants.py
- simulation/model.py
- simulation/tests/test_model.py
Added:
* A scaling factor inside the model.new_builds_per_step property that
scales according to the model.household_count in relation to the
ENGLAND_WALES_POPULATION. This means that the number of new builds is
actually scaled to the number of agents we are running
Changed:
* `ANNUAL_NEW_BUILDS` -> `ENGLAND_WALES_ANNUAL_NEW_BUILDS` so its more
explicit what the constant represents
Note: This has been tested locally, and is exhibiting the behaviour we would expect (see below) and fixes a bug introduced in #119.
> Scale the number of new builds to the agent population size

- k8s/job.jsonnet
- simulation/__main__.py
- simulation/agents.py
- simulation/constants.py
- simulation/tests/test_agents.py
* Assume that households upgrade to EPC D when they install a HP. 
* Update the initial number of HP installers based on latest data
> Update model assumptions (EPC upgrade + HP installers)

- simulation/costs.py
- simulation/tests/test_costs.py
Update BUS funding cap:
* 'Standard BUS': £237.5M until 2028. --> BUS horizon is 1 Jan 2024 (beginning of simulation) - Apr2025. Assuming £200M Apr 2024-2025 (see [announcement](https://www.gov.uk/government/publications/boiler-upgrade-scheme-approval-to-over-allocate-vouchers/approval-to-over-allocate-vouchers-for-the-boiler-upgrade-scheme-october-2024)) + £37.5M Jan-Apr 2024 given that we assume 2024 had a £150M funding cap.
* 'Extended BUS': £5.45B until 2035 --> Assuming £250M 2024-’25 + £1.54B 2025-’28 (see [announcement](https://www.gov.uk/government/news/families-business-and-industry-to-get-energy-efficiency-support)) + £515M PA 2028-2035.
> Update BUS funding cap

- k8s/job.jsonnet
Previous deploy failed because job names were too long. This PR adjusts job names and adds an additional job run.
> Add new job
